/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "example.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(my_struct, my_struct, AUTO)


PB_BIND(request, request, AUTO)


PB_BIND(response, response, AUTO)


PB_BIND(req_resp, req_resp, AUTO)


PB_BIND(status, status, AUTO)





